tap 'caskroom/cask'

brew 'git'
brew 'npm'

cask 'firefox'
cask 'google-chrome'
cask 'calibre'
cask 'slack'
cask 'station'
cask 'whatsapp'
cask 'airtable'
cask 'authy'
cask 'coconutbattery'
cask 'keybase'
cask 'notion'
cask 'visual-studio-code'
cask 'figma'
cask 'flux'
cask '1password'
cask 'osxfuse'
cask 'cryptomator'
cask 'google-drive-file-stream'
cask 'vlc'